Git integration, readme fixes, style changes
v3rse/done pull request #6
Opened 2017-10-14 01:26 UTC by jonluca

I added the git integration, fixed up some parts of the readme. and fixed some style issues like mismatched brackets and such.

let me know if you have any questions?

2017-11-01 08:56 UTC, v3rse requested changes
@jonluca Sorry for taking so long with this. Was swamped on a work project. Awesome work!! I just noticed a few things which I commented on. Again thanks.

2017-11-01 08:56 UTC, v3rse commented on done.js
> +        displayError("Not currently in a git repository!");
It would be cool if you created a git repo by running `git init`. What do you think?

2017-11-01 08:56 UTC, v3rse commented on done.js
> +            fs.writeFile(fileName, {flag: 'wx'}, function (err, data) {
I believe the options i.e. `{flag: 'wx'}` are supposed to be the third argument. The second argument is supposed to be the data written to the file. Check out the docs [here](http://devdocs.io/node/fs#fs_fs_writefile_file_data_options_callback). This currently writes `[object Object]` to the file.

2017-11-01 08:56 UTC, v3rse commented on done.js
> +            console.log("Saved commit to task " + task + 1);
I might be cool to call `check(task)` here to check the task after the commit is added.

2017-11-01 08:58 UTC, v3rse commented on done.js
> +    console.log("Usage: done [add|check|delete|help|clear [all|done]|list [all|done]] [task]");
Forgot to add this as well. We will need to add the `git` commands to the usage function

2017-11-01 09:14 UTC, v3rse commented
@jonluca Forgot to add this as well. We will need to add the git commands to the usage function.

2019-03-28 16:58 UTC, closed without merging

2019-03-28 16:58 UTC, jonluca commented
Closing this as I don't have the cycles right now. Thanks!